#!/system/bin/sh
#
#      Enable Compcache Before SWAP in a1 device
#

RAM=$(cat /proc/meminfo | grep MemTotal | awk '{print $2}')
SDSWAP=$(fdisk -l /dev/block/mmcblk0 | grep "82 Linux swap" | awk '{print $1}' | tail -n1)

handle_compcache &
sleep 2

if [ $RAM -lt "200000" ]; then

	if [[ -e /data/swapfile ]]; then
		SWAP=$(losetup -f)
		losetup $SWAP /data/swapfile
	else
		SWAP=$SDSWAP
	fi
	swapon $SWAP
fi
